In [1]:
import pandas as pd
import numpy as np
training = pd.read_csv('train.csv')
testing = pd.read_csv('test.csv')

In [2]:
training.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               1500 non-null   int64
 1   daya_baterai        1500 non-null   int64
 2   bluetooth           1500 non-null   int64
 3   kecepatan_clock     1450 non-null   float64
 4   dual_sim            1500 non-null   int64
 5   kamera_depan        1500 non-null   int64
 6   four_g              1500 non-null   object
 7   memori_internal     1500 non-null   int64
 8   tebal_hp            1500 non-null   float64
 9   berat_hp            1500 non-null   int64
 10  jumlah_prosesor     1500 non-null   int64
 11  kamera_belakang_mp  1500 non-null   int64
 12  px_panjang          1500 non-null   int64
 13  px_lebar            1500 non-null   int64
 14  kapasitas_ram       1500 non-null   int64
 15  panjang_layar       1381 non-null   float64
 16  lebar_layar         1500 non-null   int64
 17  waktu_telfon        1500 non-null   int64
 18  three_g             1500 non-null   int64
 19  touch_screen        1500 non-null   int64
 20  wifi                1500 non-null   int64
 21  price_range         1500 non-null   object
dtypes: float64(3), int64(17), object(2)
memory usage: 257.9+ KB

In [3]:
testing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   index               500 non-null    int64
 1   daya_baterai        500 non-null    int64
 2   bluetooth           500 non-null    int64
 3   kecepatan_clock     500 non-null    float64
 4   dual_sim            500 non-null    int64
 5   kamera_depan        500 non-null    int64
 6   four_g              500 non-null    object
 7   memori_internal     500 non-null    int64
 8   tebal_hp            500 non-null    float64
 9   berat_hp            500 non-null    int64
 10  jumlah_prosesor     500 non-null    int64
 11  kamera_belakang_mp  500 non-null    int64
 12  px_panjang          500 non-null    int64
 13  px_lebar            500 non-null    int64
 14  kapasitas_ram       500 non-null    int64
 15  panjang_layar       500 non-null    int64
 16  lebar_layar         500 non-null    int64
 17  waktu_telfon        500 non-null    int64
 18  three_g             500 non-null    int64
 19  touch_screen        500 non-null    int64
 20  wifi                500 non-null    int64
dtypes: float64(2), int64(18), object(1)
memory usage: 82.2+ KB

In [4]:
def null_table(train, test):
    print("Training data frame")
    print(pd.isnull(train).sum())
    print(" ")
    print("Testing data frame")
    print(pd.isnull(test).sum())

null_table(training,testing)

Training data frame
index                   0
daya_baterai            0
bluetooth               0
kecepatan_clock        50
dual_sim                0
kamera_depan            0
four_g                  0
memori_internal         0
tebal_hp                0
berat_hp                0
jumlah_prosesor         0
kamera_belakang_mp      0
px_panjang              0
px_lebar                0
kapasitas_ram           0
panjang_layar         119
lebar_layar             0
waktu_telfon            0
three_g                 0
touch_screen            0
wifi                    0
price_range             0
dtype: int64

Testing data frame
index                 0
daya_baterai          0
bluetooth             0
kecepatan_clock       0
dual_sim              0
kamera_depan          0
four_g                0
memori_internal       0
tebal_hp              0
berat_hp              0
jumlah_prosesor       0
kamera_belakang_mp    0
px_panjang            0
px_lebar              0
kapasitas_ram         0
panjang_layar         0
lebar_layar           0
waktu_telfon          0
three_g               0
touch_screen          0
wifi                  0
dtype: int64

In [5]:
training['kecepatan_clock'].fillna(training['kecepatan_clock'].mean(), inplace= True)
training['panjang_layar'].fillna(training['panjang_layar'].mean(), inplace= True)

In [6]:
null_table(training,testing)

Training data frame
index                 0
daya_baterai          0
bluetooth             0
kecepatan_clock       0
dual_sim              0
kamera_depan          0
four_g                0
memori_internal       0
tebal_hp              0
berat_hp              0
jumlah_prosesor       0
kamera_belakang_mp    0
px_panjang            0
px_lebar              0
kapasitas_ram         0
panjang_layar         0
lebar_layar           0
waktu_telfon          0
three_g               0
touch_screen          0
wifi                  0
price_range           0
dtype: int64

Testing data frame
index                 0
daya_baterai          0
bluetooth             0
kecepatan_clock       0
dual_sim              0
kamera_depan          0
four_g                0
memori_internal       0
tebal_hp              0
berat_hp              0
jumlah_prosesor       0
kamera_belakang_mp    0
px_panjang            0
px_lebar              0
kapasitas_ram         0
panjang_layar         0
lebar_layar           0
waktu_telfon          0
three_g               0
touch_screen          0
wifi                  0
dtype: int64

In [7]:
training

,index,daya_baterai,bluetooth,kecepatan_clock,dual_sim,kamera_depan,four_g,memori_internal,tebal_hp,berat_hp,...,px_panjang,px_lebar,kapasitas_ram,panjang_layar,lebar_layar,waktu_telfon,three_g,touch_screen,wifi,price_range
0,1045,531,0,1.1,0,10,Tidak,63,0.7,189,...,145,1903,2958,17.0,1,19,0,1,0,2000k-3000k
1,937,764,1,1.2,1,1,Tidak,13,1.0,152,...,361,511,3148,18.0,7,6,1,1,0,2000k-3000k
2,1658,1812,1,1.3,1,4,Ya,42,1.0,162,...,380,1550,3338,18.0,13,11,1,1,1,>3000k
3,529,1821,0,0.9,0,9,Ya,12,0.3,114,...,97,1803,2430,7.0,4,6,1,1,1,2000k-3000k
4,895,1790,1,2.3,1,3,Ya,49,0.5,100,...,396,1980,3568,6.0,2,18,1,0,1,>3000k
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,835,1224,1,1.6,0,9,Tidak,33,1.0,157,...,522,563,3796,10.0,5,13,1,1,0,>3000k
1496,1216,1158,0,0.7,1,1,Ya,29,0.7,123,...,311,1796,1542,17.0,9,15,1,0,1,1000k-<2000k
1497,1653,1190,0,2.0,1,0,Tidak,40,0.2,93,...,1399,1646,3610,13.0,7,9,0,0,1,>3000k
1498,559,1191,0,2.4,1,2,Tidak,13,0.9,169,...,179,1813,1028,14.0,6,8,1,1,1,0-<1000k
1499,684,706,0,0.5,0,13,Ya,31,0.1,108,...,543,938,2419,8.0,7,4,1,0,1,1000k-<2000k

In [8]:
from sklearn.preprocessing import LabelEncoder
le_pr = LabelEncoder()
le_pr.fit(training['price_range'])

encoded_pr = le_pr.transform(training['price_range'])
training['price_range']= encoded_pr

fg_pr = LabelEncoder()
fg_pr.fit(training['four_g'])

encoded_fg = fg_pr.transform(training['four_g'])
training['four_g']= encoded_fg

fg_pp = LabelEncoder()
fg_pp.fit(testing['four_g'])

encoded_ff = fg_pp.transform(testing['four_g'])
testing['four_g']= encoded_ff

In [9]:
training

,index,daya_baterai,bluetooth,kecepatan_clock,dual_sim,kamera_depan,four_g,memori_internal,tebal_hp,berat_hp,...,px_panjang,px_lebar,kapasitas_ram,panjang_layar,lebar_layar,waktu_telfon,three_g,touch_screen,wifi,price_range
0,1045,531,0,1.1,0,10,0,63,0.7,189,...,145,1903,2958,17.0,1,19,0,1,0,2
1,937,764,1,1.2,1,1,0,13,1.0,152,...,361,511,3148,18.0,7,6,1,1,0,2
2,1658,1812,1,1.3,1,4,1,42,1.0,162,...,380,1550,3338,18.0,13,11,1,1,1,3
3,529,1821,0,0.9,0,9,1,12,0.3,114,...,97,1803,2430,7.0,4,6,1,1,1,2
4,895,1790,1,2.3,1,3,1,49,0.5,100,...,396,1980,3568,6.0,2,18,1,0,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,835,1224,1,1.6,0,9,0,33,1.0,157,...,522,563,3796,10.0,5,13,1,1,0,3
1496,1216,1158,0,0.7,1,1,1,29,0.7,123,...,311,1796,1542,17.0,9,15,1,0,1,1
1497,1653,1190,0,2.0,1,0,0,40,0.2,93,...,1399,1646,3610,13.0,7,9,0,0,1,3
1498,559,1191,0,2.4,1,2,0,13,0.9,169,...,179,1813,1028,14.0,6,8,1,1,1,0
1499,684,706,0,0.5,0,13,1,31,0.1,108,...,543,938,2419,8.0,7,4,1,0,1,1

In [10]:
X = training.drop(['price_range'], axis =1)
y= training['price_range']

In [11]:
y

0       2
1       2
2       3
3       2
4       3
       ..
1495    3
1496    1
1497    3
1498    0
1499    1
Name: price_range, Length: 1500, dtype: int32

In [12]:
X

,index,daya_baterai,bluetooth,kecepatan_clock,dual_sim,kamera_depan,four_g,memori_internal,tebal_hp,berat_hp,...,kamera_belakang_mp,px_panjang,px_lebar,kapasitas_ram,panjang_layar,lebar_layar,waktu_telfon,three_g,touch_screen,wifi
0,1045,531,0,1.1,0,10,0,63,0.7,189,...,14,145,1903,2958,17.0,1,19,0,1,0
1,937,764,1,1.2,1,1,0,13,1.0,152,...,2,361,511,3148,18.0,7,6,1,1,0
2,1658,1812,1,1.3,1,4,1,42,1.0,162,...,15,380,1550,3338,18.0,13,11,1,1,1
3,529,1821,0,0.9,0,9,1,12,0.3,114,...,18,97,1803,2430,7.0,4,6,1,1,1
4,895,1790,1,2.3,1,3,1,49,0.5,100,...,11,396,1980,3568,6.0,2,18,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,835,1224,1,1.6,0,9,0,33,1.0,157,...,18,522,563,3796,10.0,5,13,1,1,0
1496,1216,1158,0,0.7,1,1,1,29,0.7,123,...,20,311,1796,1542,17.0,9,15,1,0,1
1497,1653,1190,0,2.0,1,0,0,40,0.2,93,...,1,1399,1646,3610,13.0,7,9,0,0,1
1498,559,1191,0,2.4,1,2,0,13,0.9,169,...,7,179,1813,1028,14.0,6,8,1,1,1
1499,684,706,0,0.5,0,13,1,31,0.1,108,...,19,543,938,2419,8.0,7,4,1,0,1

In [13]:
from sklearn.preprocessing import StandardScaler
cols = X.columns
cols2 = testing.columns

scaler = StandardScaler()
X = scaler.fit_transform(testing)
x_test = scaler.transform(testing)

X = pd.DataFrame(X, columns=cols)
x_test = pd.DataFrame(testing, columns=cols2)

In [14]:
x_test

,index,daya_baterai,bluetooth,kecepatan_clock,dual_sim,kamera_depan,four_g,memori_internal,tebal_hp,berat_hp,...,kamera_belakang_mp,px_panjang,px_lebar,kapasitas_ram,panjang_layar,lebar_layar,waktu_telfon,three_g,touch_screen,wifi
0,405,1454,1,0.5,1,1,0,34,0.7,83,...,3,250,1033,3419,7,5,5,1,1,0
1,1190,1092,1,0.5,1,10,0,11,0.5,167,...,14,468,571,737,14,4,11,0,1,0
2,1132,1524,1,1.8,1,0,0,10,0.6,174,...,1,154,550,2678,16,5,13,1,0,1
3,731,1807,1,2.1,0,2,0,49,0.8,125,...,10,337,1384,1906,17,13,13,0,1,1
4,1754,1086,1,1.7,1,0,1,43,0.2,111,...,1,56,1150,3285,11,5,17,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,936,805,0,0.8,0,1,0,34,0.6,88,...,2,1262,1538,3647,18,11,9,1,0,1
496,1524,1162,0,1.0,0,0,0,50,0.5,104,...,10,332,866,1404,10,3,15,1,1,1
497,1415,1759,1,1.4,0,10,1,15,0.4,101,...,13,382,1163,2107,18,5,16,1,1,0
498,1223,514,1,1.6,0,7,1,37,0.1,172,...,9,956,1723,3392,12,8,5,1,1,1
499,1548,1410,1,0.5,1,0,1,15,0.3,92,...,1,192,1311,2304,18,4,18,1,1,0

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score

model_rf = RandomForestClassifier()
#param_grid = {'n_estimators': [100,200,300,400,500], 'criterion':['gini','entropy'],
              # 'max_features': ['auto','sqrt','log2'],
             #  'max_depth': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
             #  'bootstrap': [True,False],'min_samples_split': [2,3,4,5,6,7,8,9,10], 'class_weight':['balanced','balanced_subsample'],
             #  'min_samples_leaf': [1,2,3,4,5]}
       
rscv = RandomizedSearchCV(model_rf, param_grid, cv=10, scoring='f1_micro')
rscv.fit(X, y)

SyntaxError: invalid syntax (<ipython-input-17-039a1875c815>, line 13)

In [ ]:
rscv.best_score_

In [ ]:
model_rf = rscv.best_estimator_

In [ ]:
y_predict = model_rf.predict(x_test)

In [ ]:
y_predict

In [ ]:
#submission = pd.DataFrame({'index':testing['index'],
                         # 'price_range':y_predict})
#submission.to_csv('fp.csv', index =False)

In [ ]:
tes = pd.read_csv('fp.csv')

In [ ]:
tes